##Removes CG dinucleotides from a coding sequence in the DNA format while preserving protein sequence

# Enter input DNA sequence
dna_sequence <- "ATGGGAAATGGGGAGTCCCAGCTGTCCTCGGTGCCTGCTCAGAAGCTGGGTTGGTTTATCCAGGAATACCTGAAGCCCTACGAAGAATGTCAGACACTGATCGACGAGATGGTGAACACCATCTGTGACGTCCTGCAGGAACCCGAACAGTTCCCCCTGGTGCAGGGAGTGGCCATAGGTGGCTCCTATGGACGGAAAACAGTCTTAAGAGGCAACTCCGATGGTACCCTTGTCCTCTTCTTCAGTGACTTAAAACAATTCCAGGATCAGAAGAGAAGCCAACGTGACATCCTCGATAAAACTGGGGATAAGCTGAAGTTCTGTCTGTTCACGAAGTGGTTGAAAAACAATTTCGAGATCCAGAAGTCCCTTGATGGGTTCACCATCCAGGTGTTCACAAAAAATCAGAGAATCTCTTTCGAGGTGCTGGCCGCCTTCAACGCTCTGAGCTTAAATGATAATCCCAGCCCCTGGATCTATCGAGAGCTCAAAAGATCCTTGGATAAGACAAATGCCAGTCCTGGTGAGTTTGCAGTCTGCTTCACTGAACTCCAGCAGAAGTTTTTTGACAACCGTCCTGGAAAACTAAAGGATTTGATCCTCTTGATAAAGCACTGGCATCAACAGTGCCAGAAAAAAATCAAGGATTTACCCTCGCTGTCTCCGTATGCCCTGGAGCTGCTTACGGTGTATGCCTGGGAACAGGGGTGCAGAAAAGACAACTTTGACATTGCTGAAGGCGTCAGAACCGTACTGGAGCTGATCAAATGCCAGGAGAAGCTGTGTATCTATTGGATGGTCAACTACAACTTTGAAGATGAGACCATCAGGAACATCCTGCTGCACCAGCTCCAATCAGCGAGGCCAGTAATCTTGGATCCAGTTGACCCAACCAATAATGTGAGTGGAGATAAAATATGCTGGCAATGGCTGAAAAAAGAAGCTCAAACCTGGTTGACTTCTCCCAACCTGGATAATGAGTTACCTGCACCATCTTGGAATGTTCTGCCTGCACCACTCTTCACGACCCCAGGCCACCTTCTGGATAAGTTCATCAAGGAGTTTCTCCAGCCCAACAAATGCTTCCTAGAGCAGATTGACAGTGCTGTTAACATCATCCGTACATTCCTTAAAGAAAACTGCTTCCGACAATCAACAGCCAAGATCCAGATTGTCCGGGGAGGATCAACCGCCAAAGGCACAGCTCTGAAGACTGGCTCTGATGCCGATCTCGTCGTGTTCCATAACTCACTTAAAAGCTACACCTCCCAAAAAAACGAGCGGCACAAAATCGTCAAGGAAATCCATGAACAGCTGAAAGCCTTTTGGAGGGAGAAGGAGGAGGAGCTTGAAGTCAGCTTTGAGCCTCCCAAGTGGAAGGCTCCCAGGGTGCTGAGCTTCTCTCTGAAATCCAAAGTCCTCAACGAAAGTGTCAGCTTTGATGTGCTTCCTGCCTTTAATGCACTGGGTCAGCTGAGTTCTGGCTCCACACCCAGCCCCGAGGTTTATGCAGGGCTCATTGATCTGTATAAATCCTCGGACCTCCCGGGAGGAGAGTTTTCTACCTGTTTCACAGTCCTGCAGCGAAACTTCATTCGCTCCCGGCCCACCAAACTAAAGGATTTAATTCGCCTGGTGAAGCACTGGTACAAAGAGTGTGAAAGGAAACTGAAGCCAAAGGGGTCTTTGCCCCCAAAGTATGCCTTGGAGCTGCTCACCATCTATGCCTGGGAGCAGGGGAGTGGAGTGCCGGATTTTGACACTGCAGAAGGTTTCCGGACAGTCCTGGAGCTGGTCACACAATATCAGCAGCTCTGCATCTTCTGGAAGGTCAATTACAACTTTGAAGATGAGACCGTGAGGAAGTTTCTACTGAGCCAGTTGCAGAAAACCAGGCCTGTGATCTTGGACCCAGCCGAACCCACAGGTGACGTGGGTGGAGGGGACCGTTGGTGTTGGCATCTTCTGGCAAAAGAAGCAAAGGAATGGTTATCCTCTCCCTGCTTCAAGGATGGGACTGGAAACCCAATACCACCTTGGAAAGTGCCGACAATGCAGACACCAGGAAGTTGTGGAGCTAGGATCCATCCTATTGTCAATGAGATGTTCTCATCCAGAAGCCATAGAATCCTGAATAATAATTCTAAAAGAAACTTCTAG"

# Load tables and functions
codon_table <- list(
  'TTT'='F', 'TTC'='F', 'TTA'='L', 'TTG'='L', 'CTT'='L', 'CTC'='L', 'CTA'='L', 'CTG'='L',
  'ATT'='I', 'ATC'='I', 'ATA'='I', 'ATG'='M', 'GTT'='V', 'GTC'='V', 'GTA'='V', 'GTG'='V',
  'TCT'='S', 'TCC'='S', 'TCA'='S', 'TCG'='S', 'CCT'='P', 'CCC'='P', 'CCA'='P', 'CCG'='P',
  'ACT'='T', 'ACC'='T', 'ACA'='T', 'ACG'='T', 'GCT'='A', 'GCC'='A', 'GCA'='A', 'GCG'='A',
  'TAT'='Y', 'TAC'='Y', 'TAA'='*', 'TAG'='*', 'CAT'='H', 'CAC'='H', 'CAA'='Q', 'CAG'='Q',
  'AAT'='N', 'AAC'='N', 'AAA'='K', 'AAG'='K', 'GAT'='D', 'GAC'='D', 'GAA'='E', 'GAG'='E',
  'TGT'='C', 'TGC'='C', 'TGA'='*', 'TGG'='W', 'CGT'='R', 'CGC'='R', 'CGA'='R', 'CGG'='R',
  'AGT'='S', 'AGC'='S', 'AGA'='R', 'AGG'='R', 'GGT'='G', 'GGC'='G', 'GGA'='G', 'GGG'='G'
)

alternative_codons <- list()
for (codon in names(codon_table)) {
  aa <- codon_table[[codon]]
  if (!grepl("CG", codon)) {
    alternative_codons[[aa]] <- c(alternative_codons[[aa]], codon)
  }
}

# This function removes CGs 
remove_CG <- function(dna_seq) {
  codons <- strsplit(dna_seq, "(?<=...)", perl=TRUE)[[1]]
  for (i in seq_along(codons)) {
    aa <- codon_table[[codons[i]]]
    
    if (grepl("CG", codons[i])) {
      codons[i] <- sample(alternative_codons[[aa]], 1)
    }
    
    if (i > 1 && substr(codons[i-1], 3, 3) == "C" && substr(codons[i], 1, 1) == "G") {
      prev_aa <- codon_table[[codons[i-1]]]
      valid_replacements <- setdiff(alternative_codons[[prev_aa]], codons[i-1])
      if (length(valid_replacements) > 0) {
        codons[i-1] <- sample(valid_replacements, 1)
      }
    }
  }
  return(paste(codons, collapse=""))
}

# Process and export sequence
new_dna_sequence <- remove_CG(dna_sequence)
writeLines(new_dna_sequence, "modified_sequence.txt") #Enter name of recoded sequence output

